### ISSUE TITLE
gf2.h not found

### ISSUE THREAD

**Issue by bobmB** [sleepybishop/nanorq#18] opened 2023-09-21 16:54 UTC
Hi,
I've added your oblas libraries under deps, but it doesn't contain the gf2.h file.  When I try to make nanorq I get the following error:
In file included from include/precode.h:8:0,
                 from lib/precode.c:1:
include/wrkmat.h:7:10: fatal error: gf2.h: No such file or directory
 #include "gf2.h"
          ^~~~~~~

Where can I get gf2.h. please?
Bob.

**Comment by sleepybishop** [comment] 2023-09-21 17:29
Hi, please see https://github.com/sleepybishop/nanorq/issues/16

Duplicate of #16

**Closed as not planned by sleepybishop** 2023-09-21 17:29 UTC
